### ISSUE TITLE
Additional Problems > File not found errors

### ISSUE THREAD

**Issue by JoshBaron** [oaeproject/Hilary#1142]
We are experiencing additional problems which may be related to the other one.

When I attempt to click on certain file icons from my home page to files that were just uploaded within the last hour or so I'm getting 404 error messages.
One example is at: https://marist.oaeproject.org/content/marist/XJEtxESF
Another one is at: https://marist.oaeproject.org/content/marist/718dXmHY

This is a more serious issue as we cannot access files at this point.

I'm attaching a screen shot with circles around the icons I'm clicking.
![capture2](https://cloud.githubusercontent.com/assets/5169198/6641154/8ccd2464-c972-11e4-89af-472dac69011a.JPG)

**Comment by nicolaasmatthijs** [comment]
@JoshBaron : It looks like the `LAK15 Shuttle` only contains 2 items:

- LAK15_Airport_Shuttle_TXT_Print.pdf
- LAK15_MASTER_Shuttle_Survey_03_11_15_...

The `LAK15 Shuttle PDFs` and `LAK15_JFK_TXT_PRINT` documents appear to have been deleted from the system or at least removed from the folder, which is why you're unable to access to them.

They still appear in your activity feed as they were originally added to that folder.

Can you confirm that these items no longer being a part of that folder is expected behavior?

**Comment by JoshBaron** [comment]
Ah, that could be the case...confirming now, I'll update you soon.
-----------------------------
Joshua Baron
Assistant Vice President, Information Technology for Digital Education
Marist College
Poughkeepsie, New York  12601
(845) 575-3623 (work)
Twitter: JoshBaron

**Comment by nicolaasmatthijs** [comment]
Some further analysis suggests that they have been deleted.

**Comment by JoshBaron** [comment]
OK, I've checked with Dede (who is the one uploading those files) and yes, you are correct, she had uploaded and then deleted some files which would explain things.  Apologies for the confusion, the fact that I was seeing these just after the fix was rolled out triggered some concern.

So, I think things are resolved at this point, thanks for the quick response!
