### ISSUE TITLE
Investigate DataStax their cassandra driver

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1146]
As Helenus (our old Cassandra driver) doesn't even build anymore on node 0.12. we should look into switching it out for [DataStax their driver](https://github.com/datastax/nodejs-driver).

UeberDB just removed support for Cassandra which makes upgrading Etherpad now harder than it should be. Attempting an upgrade in UeberDB might be a good test-case anyway.

**Comment by simong** [comment]
ueberDB now uses datastax their driver

**Comment by mrvisser** [comment]
I looked into this a bit and wrote a bit of code to get the process started: https://github.com/oaeproject/Hilary/compare/026afcf14626b56f4ffe99fb9185c42b8dd2455b...ba4f3a43b850381e4f3f00685d93ecb51384b200

Here are some notes:

1. It's a bit simpler to use, getting keyspace metadata is done automatically which helps with some of the things we do w/ lookup the keyspace and tables
2. We lose support for the nice `IN` clause parameter handling by being able to specify an array as a parameter: `WHERE "id" IN (?)`, [['id1', 'id2',...]]`. So we either have to do something on our own to expand that into: `WHERE "id" IN (?, ?, ...)`, ['id1', 'id2', ...]` or do a specialized function for an "IN" query (which I've done in the above diff). We should be careful with trying to intelligently handle arrays in the parameter list because Cassandra has more types than it does before that we may want to use
3. We're going to run into type-related things. For example the field `Principals.created` in our schema is a `timestamp`, but we seem to persist a string millis since epoch "1234567890" in some areas, which binary protocol is rejecting. It looks like Thrift was allowing it, but that does seem sketchy. We'll have wade through all those things to get it working

That's as far as I got before I bailed as I probably won't get a full coherent PR for it in the next couple weeks.

**Comment by mrvisser** [comment]
Also, automatic node discovery and retry policies are awesome.

Also interested to see what we could do with UDT's.

**Comment by simong** [comment]
I've got a PR going at https://github.com/oaeproject/Hilary/pull/1228 which should add basic API compatibility. I haven't looked into things like retry policies yet

**Comment by nicolaasmatthijs** [comment]
Now tracking at https://github.com/oaeproject/Hilary/pull/1228
