### ISSUE TITLE
Share via email - redundant access

### ISSUE THREAD

**Issue by sathomas** [oaeproject/Hilary#1221]
1. Logged in using Twitter and confirmed my email address as `stephen.thomas@et.gatech.edu`.
2. Uploaded a document and shared that document with `stephen.thomas@et.gatech.edu`.
3. Document now lists two users even though they are the same account.

![safari - oae oae-qa1 oaeproject org - - screen shot aug 4 2015 10 59 29 am](https://cloud.githubusercontent.com/assets/1731910/9064088/ef52b40e-3a98-11e5-81ec-f7358ac7b950.png)

**Comment by mrvisser** [comment]
A couple things that are in progress:

1. We are making it so that you can't just type in an existing email address and share with it. You must pick from the selection
2. In cases where a bulk number of email addresses are entered VIA comma-separation, on the server-side we will be getting user accounts associated to the emails. If an email has only 1 account associated, we will use that account; If there are multiple, it will be treated as a regular email invite

I suppose there is more we can do to check if the email is associated to the current user account and reject the share w/ a 400, though I should note that accepting an email invitation to something you are already a member of is harmless.

**Comment by mrvisser** [comment]
This work is complete.
