### ISSUE TITLE
share via email - account confusion

### ISSUE THREAD

**Issue by sathomas** [oaeproject/Hilary#1222]
1. Signed in via Twitter (using email `stephen.thomas@et.gatech.edu`).
2. Shared document with myself using a different email address.
3. After clicking on the `Accept this invitation` button in the email message, logged in using Twitter again (not the second email address).

I'm not exactly sure what happened, but it looks like I now have an account on the Guest tenant in addition to the main tenant. Perhaps this is working as designed, but I'm not sure there aren't other messy implications.

![safari - guest oae-qa1 oaeproject org - - screen shot aug 4 2015 11 11 44 am](https://cloud.githubusercontent.com/assets/1731910/9064279/c2d3cd5e-3a99-11e5-9b7d-6c294833ef48.png)

**Comment by mrvisser** [comment]
@sathomas you were taken to the guest tenant because the second email address you used (a gmail one?) didn't know what tenant you belonged to by using just an email address.

There are messy implications, and it would be better to have a WAYF type service, but that is intentionally out-scoped currently to expedite the ability to have users invite others into the system.

I'll be closing this as WAYF is identified as a priority.
