### ISSUE TITLE
Provide configuration option for inviting guests from guest tenancy

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1252]
ESUP has reported that they would like to prevent users on the guests tenancy from inviting new guests.

**Comment by simong** [comment]
Is this just for the guests tenancy or would specific tenants also like to disable inviting guests?

**Comment by mrvisser** [comment]
I think this still needs a bit more analysis. They probably also want the network tenant to be invitiation-only, then. Right?

**Comment by mrvisser** [comment]
Also, why shouldn't someone from the guest tenant be able to share with an email that is associated with a tenant they are collaborating with?

**Comment by nicolaasmatthijs** [comment]
@dooremont : there are a number of questions around this feature:

- Do you want people to be able to sign up to the guest tenant themselves or should it be invitation only?
- Why shouldn't a user from the guest tenant be able to share with an email addresses associated with a proper tenant?

**Comment by dooremont** [comment]
*Do you want people to be able to sign up to the guest tenant themselves 
or should it be invitation only?*
I prefer that people can not sign up to the guest to taking Themselves


*Why shouldn't a user from the guest tenant be able to share with an email addresses associated with a proper tenant?*
I think there is a security problem, I do not prefer that people of the guest tenant can launch an invitation. For not to have the whole world belongs "to the guest tenant" ;-)

**Comment by matguerin** [comment]
*Why shouldn't a user from the guest tenant be able to share with an email addresses associated with a proper tenant?*
Not sure it is necessary but I would add to Fred's answer that people of the guest tenant should still be able to invite existing people or people (even if they don't exist yet) from "real" tenants (by checking the e-mail domain)... But they should be not able to invite other "guests" on the "guest tenant" otherwise, like Fred said, everyone with a valid e-mail will be able to have an account on the guest tenant (as long as they know someone with one) and this is something we definitely don't want.

**Comment by dooremont** [comment]
@matguerin 
thanks for the add ;-)

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by dooremont** [comment]
Hi Nicolaas 
Great News 
Thank a lot
Kind regards

Frédéric Dooremont

**Comment by nicolaasmatthijs** [comment]
This was implemented at https://github.com/oaeproject/Hilary/pull/1277
