### ISSUE TITLE
Images disappeared from folder

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1266]
```
This is the person who uploaded the images for Diwali but they disappeared: https://marist.oaeproject.org/user/marist/E1o6x24o

Her images with the sand art were loaded in the Diwali folder - he myDiwali Celebration group and to the "pictures of "mydiwali #mymarist" folder prior to November 16th
```

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment]
The issue is that the first 41 content items in this folder library are deleted. The UI requests the first 12 items, and it returns an empty array with a valid `nextToken`, however 3akai-ux doesn't attempt to request any more items after the first batch.

The bug is likely that the UI is keying off of the length of the results array instead of the status of `nextToken` to determine when to stop paging.

I'll open a 3akai-ux ticket to fix the paging bug, I'll purge the folder library in production so it can rebuild.

We also may want to change the back-end to be able to do the refetch there and repair deleted items. The reason for this is that I don't think it's great for the UI to have to do 4 requests before it can start getting valid library items in these sorts of cases.

**Comment by mrvisser** [comment]
3akai-ux issue created: https://github.com/oaeproject/3akai-ux/issues/4089

I've also purged the library in production and the folder once more has content.

This ticket is being left open to track the need for:

> We also may want to change the back-end to be able to do the refetch there and repair deleted items.

**Comment by nicolaasmatthijs** [comment]
This has now been completed
