### ISSUE TITLE
Rest API Version fails for git based installs

### ISSUE THREAD

**Issue by davidoae** [oaeproject/Hilary#1397]
The version API reports fine when Hilary/3akai-ux are packages but when they're git checkouts the version tool always seems to say "Could not get the branch information".
It would be great if it would display the branch and maybe also the commit.

**Comment by brecke** [comment]
I think I know what's going on. Tell me: have the repos been cloned recently, as in, after release 13.0?

If so, then one needs to `git checkout master` in each of the submodules for that to work. It's git's default behaviour because submodules actually reference a specific commit, not a branch. As a consequence, they are checked out in "detached head" mode.

We could actually solve this issue (as described [here](https://stackoverflow.com/questions/18770545/why-is-my-git-submodule-head-detached-from-master)) if needed.

**Comment by davidoae** [comment]
This happened before the 13 release, in fact I'm not sure it's ever worked.
qa0 has the latest git deployment atm.
checking .gitmodules I see 3akai-ux and node_modules/oae-rest
I did a git checkout master in both of those;
root@qa0:/opt/oae/3akai-ux# git checkout master
Previous HEAD position was 4dd3d4e... Refinements to nginx HTTPS support
Switched to branch 'master'
root@qa0:/opt/oae/node_modules/oae-rest# git checkout master
M	3akai-ux
M	config.js
Already on 'master'

But the API reports the same error.

**Comment by brecke** [comment]
@davidoae this *may* be fixed now, could you check this again sometime?

**Comment by brecke** [comment]
Update: this works flawlessly now, but we don't currently change the commit because we don't need it.
