### ISSUE TITLE
Ability to sort search results by name in search view

### ISSUE THREAD

**Issue by brecke** [oaeproject/Hilary#1401]
From [uservoice](https://oaeproject.uservoice.com/forums/249738-open-academic-environment/suggestions/7360828-sorting-search-results):

> Search results should be sorted by relevance by default, and alternate options to sort them by tenancy, date added etc. should be present.

This is kind of a follow-up to https://github.com/oaeproject/Hilary/issues/1162.

**Comment by sallakarppinen** [comment]
I've been looking into this and some of the sorting options are more difficult than others, so we should list which ones are desirable... For example, sorting by name or tenancy is much easier than by date added since we don't currently store that data in elasticsearch (or even in Cassandra for every type of content if I recall correctly). I'd also want clarification on whether this task includes sorting in a user's library as well as search results.

**Comment by brecke** [comment]
Okay, so let's list the types of sorting that would make sense and go from there. Based on your description, we've got:

- [ ] Sort by name (asc / desc)
- [ ] Sort by tenant (asc / desc)
- [ ] Sort by date (newest / oldest)
- [ ] ...

Any others?

Then, which of those are feasible in the short term / medium term? According to that, we'll edit this issue's title and create another issue for later, depending on how things go.

**Comment by sallakarppinen** [comment]
`Sort by name` and `sort by tenant` are relatively easy. `Sort by date` - which date do we mean, `date created` or `date modified`? We don't seem to have `date created` for anything in elasticsearch, and only have `date modified` for some types and in a difficult-to-reach format. I'd probably start with `sort by name` since it's easier and can be applied to both searches and library, then move to `sort by tenant` and leave `sort by date` for later.

**Comment by brecke** [comment]
Let's do that then 👍 

Please include a reference for the complementary issue to be created in a comment.

**Comment by sallakarppinen** [comment]
Renamed this because we also have #1408
