### ISSUE TITLE
Upgrade Elasticsearch

### ISSUE THREAD

**Issue by brecke** [oaeproject/Hilary#2094]
Alteratively to upgrading (the server, the library and the deployment) we can try and reduce complexity by replacing it altogether with something like [meilisearch](https://www.meilisearch.com/) or [typesense](https://typesense.org/).

EDIT: Meilisearch is using promises 😐

TODO:

- [x] `_extra` no longer exists, do something about it
- [x] Tests passing
  - [x] `oae-principals` 3 failing tests
  - [x] Skipped test 1: `verify private unjoinable group is propagated to content managers`
  - [x] Skipped test 2: `verify get content data (collabdoc, collabsheet, link, uploaded file`
  - [x] Stalled test: ` verify the activity entities format can be specified`
- [x] Reformat testing files:
	- [x] oae-content
	- [x] oae-search
	- [x] oae-messagebox
	- [x] oae-discussions (XO only)
	- [x] oae-doc
 	- [x] oae-google-analytics
	- [x] oae-folders (XO only)
	- [x] oae-principals
	- [x] oae-context
	- [x] oae-config
	- [x] oae-email
	- [x] oae-emitter
	- [x] oae-logger
	- [x] oae-library (XO only)
	- [x] oae-lti
	- [x] oae-activity (XO only)
	- [x] oae-authentication (XO only)
	- [x] oae-authz (XO only)
	- [x] oae-preview-processor (XO only)
	- [x] oae-telemetry
	- [x] oae-tenants (XO only)
	- [x] oae-tincanapi
	- [x] oae-ui
	- [x] oae-util (XO only)
	- [x] oae-jitsi (XO only)
	- [x] oae-version
- [x] Adapt `circleCI` to use specific DNS entries for `cam` and `gt` (globals)
- [x] Rewrite JSDoc / General comments on `elasticsearch.js` etc
- [x] Monodraw diagram for revisiting this later on
- [x] Revisit all `// TODOs`
- [x] Adapt deployment script
- [x] Elasticsearch 7.8 -> 7.9
- [x] Re-add telemetry to elasticsearch methods
- [x] Extend XO settings to tests
- [x] `verify the activity entities format can be specified`
- [x] Subscribe issues related to [redlock](https://github.com/mike-marcacci/node-redlock/issues)
- [x] Read [this](https://livecodestream.dev/post/2020-10-26-a-quick-introduction-to-elasticsearch-for-node-developers/)

**Comment by jasonbosco** [comment]
👋 I work on Typesense. Let me know if I can help in any way as you explore Typesense.

**Comment by brecke** [comment]
> 👋 I work on Typesense. Let me know if I can help in any way as you explore Typesense.

Hey there. Not a good timing to replace ES altogether, but since you're here, maybe you can tell me about other people's experiences on replacing ES with typesense?

**Comment by jasonbosco** [comment]
At a high-level, Typesense is meant to be a simpler-to setup, run and scale alternative to ElasticSearch. Unlike ES, Typesense comes optimized out-of-the-box for handling typo-tolerant instance search experiences (<50ms). To enable this performance, it holds the entire index in memory. 

Now, given this architecture, there are cases like log data where using Typesense will become expensive since you'd need machines with extremely large RAM to hold the entire log dataset in memory and so ES would be a better fit. For other use cases, Typesense is now full-featured enough to give you equivalent features. Do you have a specific set of features that you use with ES? I can then tell you if Typesense can support them.

Separately, Typesense is also optimized to minimize the ops overhead of deploying a search server. It comes as a single self-contained binary and can be run in a cluster mode with minimal configuration. It also has a high-scale HTTP server built-in with authentication, so you can expose it directly to internet-facing traffic. 

In my benchmarks, I've tested a dataset with ~3 million records (Amazon product data) that was ~13GB on disk and I was able to get a throughput of 250 concurrent search queries per second on a 16GB, 8-vCPU 3-node Typesense cluster.
